Restaurant
karthi07/restaurant_page_js pull request #1
Opened 2020-07-06 14:24 UTC by karthi07

Project to practice DOM manipulation by dynamically rendering a simple restaurant homepage!  using JavaScript alone to generate the entire contents of the website!

2020-07-07 01:50 UTC, bellom requested changes
## Hi @ :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**


### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-07-07 01:50 UTC, bellom commented on src/index.js
> +<main class="container" id="main"></main>
Your design has absolutely no problem on its own, but however, you did not respect the guidelines. There are some lessons the guidelines wants us to learn, that's why we should follow it.

![image](https://user-images.githubusercontent.com/31897434/86684686-af2e5580-bffa-11ea-863a-e7df4e949cc5.png)


In other words;
**You need to append each element not hard coding them.**
kindly make use of `document.createElement` and `document.appendChild`
Example: 
`div.appendChild(Navbar)`

2020-07-07 01:50 UTC, bellom commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
We should be able to run common commands like `build`, `development` should be in `package.json` inside \`scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/)) in our own case here, we are missing it so I can't run `npm run build ` to generate `dist folder`, I should be able to run `npm run build` to generate `dist folder` at my end, currently using the one created by you, it shouldn't be like that.
kindly add these two scripts `build` and `development`

2020-07-07 18:52 UTC, Forison requested changes
## Status:: Change required❌
# 🙋‍♂️ Karthick !!!
#### Good job on implementing the issues raised on the previous review, however, there was an issue you did not address quite well🤗 .
* [ ] It appends HTML elements to the `<div>` with `id=content` when the page is loaded (Use `document.createElement` and `document.appendChild` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/append_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))
- To reinterate what was mention in the previous review, your HTML element must be created with javaScript and then appended to the DOM of the elements in index.js. 
For example instead creating elements with HTML like
``` <div class="container"></div>```
 rather do it this way
```
const container = document.createElement('div');
container.classList.add('container');
```
> This project seeks to test your understanding on JS dom manipulations
## That is it kindly make this change and submit the project for a re-review😎.
#### Happy coding 👨🏼‍💻.
Addo Forison

2020-07-08 15:55 UTC, karthi07 commented
@Forison  I believe the Requirement is to keep the div with id content should be in HTML and contents of the div should be appended via JS (It is already implemented )

2020-07-08 18:01 UTC, shshamim63 requested changes
## :clubs: Required Changes :clubs: 
___
Hi @karthi07 :wave: ,
Awesome job, your page is simple but attractive :open_mouth: . Nav links are properly functional :sunglasses: . Webpack is doing the right job. You have generated most of the tasks that are actually needed to generate the page. But a little bit of task is blocking me to approve it right now. Let's get to it.
___
### :spades: Mandatory Changes :spades: 
___
- Please replace the HTML block code with proper JS format. I know it will take you to do a lot of things. But it will help you to ensure that you know how to deal with the big projects by following pure JS conventions. And is an easy job jor you.
___
##### Please fix the issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-07-08 18:01 UTC, shshamim63 commented on src/contact.js
> +</div>`;
You are assigning HTML block in a variable in then you are using it properly. But if you check the requirement it says you have to generate each element by using JS.
![image](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/append_requirement.png)
I have searched for it and found that it is reffering to the [DOM manipulation](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction).
So if you look at this [link](https://www.w3schools.com/js/js_htmldom_nodes.asp) you will get an idea on how to generate them properly. That is what the previous reviewers trying to mention. So, please create elements by using it.

2020-07-08 18:01 UTC, shshamim63 commented on src/home.js
> +</div>`;
same as above...

2020-07-08 18:01 UTC, shshamim63 commented on src/index.js
> +  </div>`;
same as above....

2020-07-08 18:01 UTC, shshamim63 commented on src/order.js
> +</div>`;
Same as above....

2020-07-08 19:22 UTC, Forison commented
> @Forison I believe the Requirement is to keep the div with id content should be in HTML and contents of the div should be appended via JS (It is already implemented )

The point of this project is to apply the concept of JavaScript DOM manipulation instead of equating a bunch of JS code to a variable. Your page is good, but you are missing the learning objective.

2020-07-16 10:44 UTC, closed without merging